Repository Caleydo/coral, pull requests merged in 2022-10, with the labels that each got.

#45 Merged `d3_changes` into `develop`
  package.json
  src/CohortRepresentations.ts
  src/Taskview/SearchBar.ts
  src/Taskview/SearchColumn.ts
  src/Taskview/columns/AColumn.ts
  src/Taskview/columns/AttributeColumn.ts
  src/Taskview/columns/CohortColumn.ts
  src/Taskview/columns/NumberColumn.ts
  src/Taskview/tasks/ATask.ts
  src/Taskview/tasks/Compare.ts
  src/Taskview/tasks/Details.ts
  src/Taskview/tasks/Filter.ts
  src/Taskview/tasks/Prevalence.ts
  src/Taskview/visualizations/AVegaVisualization.ts
  src/Taskview/visualizations/DensityPlot.ts
  src/Taskview/visualizations/GroupedBoxplot.ts
  src/Taskview/visualizations/KaplanMeierPlot.ts
  src/Taskview/visualizations/MultiAttributeVisualization.ts
  src/Taskview/visualizations/Scatterplot.ts
  src/app.ts
  src/common/config.ts
  src/data/Attribute.ts
  src/index.ts
  src/util.ts
  src/utilLabels.ts
  src/utils/RouterScrollToTop.tsx
  src/utils/index.ts
Labels: priority: medium

#48 Automatically select root cohort if onboarding was already done
  src/app.ts
Labels: priority: low, release: patch, type: feature

#49 Remove grid lines from visualizations
  src/Taskview/visualizations/DensityPlot.ts
  src/Taskview/visualizations/GroupedBoxplot.ts
  src/Taskview/visualizations/KaplanMeierPlot.ts
  src/Taskview/visualizations/Scatterplot.ts
Labels: release: minor, type: feature
